language: php

before_script:

  # Packages
  - sudo apt-get update
  - sudo apt-get install -y apache2 libapache2-mod-php5 php5-curl php5-gd php5-mcrypt php5-mysql
  - sudo a2enmod rewrite

  # Database and sample data
  - wget -O magento-sample-data-1.6.1.0.tar.gz http://www.magentocommerce.com/downloads/assets/1.6.1.0/magento-sample-data-1.6.1.0.tar.gz
  - tar -xzf magento-sample-data-1.6.1.0.tar.gz
  - mysql -uroot -e 'CREATE DATABASE 'magento';'
  - mysql -uroot magento < magento-sample-data-1.6.1.0/magento_sample_data_for_1.6.1.0.sql

  # Apache virtual host
  - sudo cp -f build/apache /etc/apache2/sites-available/manager.conf
  - sudo sed -e "s?%BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/manager.conf
  - sudo a2ensite manager.conf
  - sudo service apache2 restart
  - sudo sh -c 'echo "127.0.0.1 manager.dev" >> /etc/hosts'

  # Install
  - composer install --prefer-source
  - php -f vendor/magetest/magento/src/install.php -- --license_agreement_accepted yes --locale en_GB --timezone Europe/London --default_currency GBP --db_host localhost --db_name magento --db_user root --db_pass "" --url http://manager.dev/ --skip_url_validation yes --use_rewrites yes --use_secure no --secure_base_url --use_secure_admin no --admin_firstname admin --admin_lastname admin --admin_email admin@example.com --admin_username admin --admin_password adminadmin123123

script: vendor/bin/phpspec r && vendor/bin/phpunit -v --coverage-clover=coverage.clover
